Name:           ros-indigo-socketcan-bridge
Version:        0.6.7
Release:        0%{?dist}
Summary:        ROS socketcan_bridge package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/socketcan_bridge
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-can-msgs
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-socketcan-interface
BuildRequires:  ros-indigo-can-msgs
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-roslint
BuildRequires:  ros-indigo-rostest
BuildRequires:  ros-indigo-rosunit
BuildRequires:  ros-indigo-socketcan-interface

%description
Provides nodes to convert messages from SocketCAN to a ROS Topic and vice versa.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Mar 28 2017 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.6.7-0
- Autogenerated by Bloom

* Sat Mar 18 2017 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.6.6-0
- Autogenerated by Bloom

* Sat Dec 10 2016 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.6.5-1
- Autogenerated by Bloom

* Sat Dec 10 2016 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.6.5-0
- Autogenerated by Bloom

