Name:           ros-lunar-canopen-402
Version:        0.7.5
Release:        0%{?dist}
Summary:        ROS canopen_402 package

Group:          Development/Libraries
License:        LGPLv3
URL:            http://wiki.ros.org/canopen_402
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-canopen-master
Requires:       ros-lunar-class-loader
BuildRequires:  ros-lunar-canopen-master
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-class-loader
BuildRequires:  ros-lunar-rosunit

%description
This implements the CANopen device profile for drives and motion control. CiA(r)
402

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Mon May 29 2017 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.7.5-0
- Autogenerated by Bloom

* Tue Apr 25 2017 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.7.4-0
- Autogenerated by Bloom

* Tue Apr 25 2017 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.7.3-0
- Autogenerated by Bloom

* Tue Apr 25 2017 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.7.2-0
- Autogenerated by Bloom

