Name:           ros-indigo-canopen-master
Version:        0.6.6
Release:        0%{?dist}
Summary:        ROS canopen_master package

Group:          Development/Libraries
License:        LGPLv3
URL:            http://wiki.ros.org/canopen_master
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-indigo-class-loader
Requires:       ros-indigo-socketcan-interface
BuildRequires:  boost-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-class-loader
BuildRequires:  ros-indigo-rosunit
BuildRequires:  ros-indigo-socketcan-interface

%description
CiA(r) CANopen 301 master implementation with support for interprocess master
synchronisation.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sat Mar 18 2017 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.6.6-0
- Autogenerated by Bloom

* Sat Dec 10 2016 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.6.5-1
- Autogenerated by Bloom

* Sat Dec 10 2016 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.6.5-0
- Autogenerated by Bloom

* Fri Jul 03 2015 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.6.4-0
- Autogenerated by Bloom

* Fri Jul 03 2015 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.6.3-0
- Autogenerated by Bloom

* Thu Dec 18 2014 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.6.2-0
- Autogenerated by Bloom

* Mon Dec 15 2014 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.6.1-0
- Autogenerated by Bloom

