%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-socketcan-bridge
Version:        0.8.2
Release:        1%{?dist}
Summary:        ROS socketcan_bridge package

License:        BSD
URL:            http://wiki.ros.org/socketcan_bridge
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-can-msgs
Requires:       ros-melodic-rosconsole-bridge
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-socketcan-interface
BuildRequires:  ros-melodic-can-msgs
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-rosconsole-bridge
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roslint
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-rosunit
BuildRequires:  ros-melodic-socketcan-interface

%description
Conversion nodes for messages from SocketCAN to a ROS Topic and vice versa.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Mon Nov 04 2019 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.8.2-1
- Autogenerated by Bloom

* Sun Jul 14 2019 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.8.1-1
- Autogenerated by Bloom

* Wed Jul 11 2018 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.8.0-0
- Autogenerated by Bloom

